### ISSUE TITLE
Failed to run smoothly, can you help? Thank you

### ISSUE THREAD

**Issue by jiashenke** [ausathe/document-translate#1]
![20200415](https://user-images.githubusercontent.com/54965169/79317321-2db5b280-7f38-11ea-95e5-dd794ae9b964.png)

Failed to run smoothly, can you help? Thank you

**Comment by ausathe** [comment]
There seems to be some problem with your selenium webdriver. Have you placed the chromedriver.exe in the folder? (If you are using some other browser, which browser are you using?)

**Comment by jiashenke** [comment]
Thank you for your reply. The file is already in the folder. I am using the latest version of Google ’s browser, Chrome, which still cannot be executed.
![20200424](https://user-images.githubusercontent.com/54965169/80187084-9fc97e00-8641-11ea-91c3-47b811a1826b.png)

**Comment by linhvu97vn** [comment]
I had the same issue.

**Comment by linhvu97vn** [comment]
Requirement already satisfied: pypdf2 in c:\users\vutli\appdata\local\programs\python\python36\lib\site-packages (1.26.0)
Requirement already satisfied: selenium in c:\users\vutli\appdata\local\programs\python\python36\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\vutli\appdata\local\programs\python\python36\lib\site-packages (from selenium) (1.25.9)
Requirement already satisfied: pyautoit in c:\users\vutli\appdata\local\programs\python\python36\lib\site-packages (0.6.0)
Requirement already satisfied: wkhtmltopdf in c:\users\vutli\appdata\local\programs\python\python36\lib\site-packages (0.2)
STEP 1: Splitting pdfs appropriately...
                                                   ...Completed
STEP 2: Connecting with translate...

DevTools listening on ws://127.0.0.1:55661/devtools/browser/de58c1c2-044e-4bd4-99c0-980fcf93fd0a
                                                   ...Completed
STEP 3: Starting main sequence...
Traceback (most recent call last):
  File "C:\Users\vutli\OneDrive\Desktop\document-translate-master\doctranslate.py", line 99, in <module>
    main()
  File "C:\Users\vutli\OneDrive\Desktop\document-translate-master\doctranslate.py", line 89, in main
    main_process(gtrans, cwd, file, 'en', 'vi')
  File "C:\Users\vutli\OneDrive\Desktop\document-translate-master\doctranslate.py", line 46, in main_process
    driver.get("https://translate.google.com/#view=home&op=docs&sl={}&tl={}".format(fromlang,tolang))
  File "C:\Users\vutli\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\vutli\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\vutli\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 4.154
  (Session info: chrome=83.0.4103.116)
